# Generated by Django 4.2.13 on 2026-07-02 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scuola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codice_meccanografico', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('numero_studenti_quinto', models.PositiveIntegerField(default=0)),
                ('numero_studenti_quarto', models.PositiveIntegerField(default=0)),
                ('numero_studenti_triennio', models.PositiveIntegerField(default=0)),
                ('numero_fsl_da_attivare', models.PositiveIntegerField(default=0)),
                ('numero_fsl_attivati', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scuola_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('doti_disponibili', models.PositiveIntegerField(default=0)),
                ('servizi_extra', models.TextField(blank=True, max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('settore', models.CharField(blank=True, max_length=120)),
                ('referente_contatti', models.CharField(blank=True, max_length=255)),
                ('numero_scoperture', models.PositiveIntegerField(default=0)),
                ('fsl_attivati_anni', models.CharField(blank=True, max_length=120)),
                ('foto', models.FileField(blank=True, null=True, upload_to='aziende_foto/')),
                ('video', models.URLField(blank=True, null=True)),
                ('ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aziende', to='portal.ente')),
            ],
        ),
    ]
