# Generated by Django 4.2.13 on 2026-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='fsl_attivati_anno_in_corso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='azienda',
            name='fsl_attivati_totale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='azienda',
            name='note',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
