# Generated by Django 4.2.13 on 2026-07-17 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_azienda_fsl_attivati_anno_in_corso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaScuola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scuola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_scuola', to='portal.scuola')),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='NotaEnte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_ente', to='portal.ente')),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
    ]
