# Generated by Django 4.2.13 on 2026-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notascuola_notaente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaente',
            name='operatore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notascuola',
            name='operatore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
