# Generated by Django 4.2.13 on 2026-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_notaente_operatore_notascuola_operatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuola',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('LICEO', 'Liceo'), ('TECNICO', 'Istituto Tecnico'), ('PROFESSIONALE', 'Istituto Professionale')], max_length=50, verbose_name='Tipologia di istituto'),
        ),
    ]
