# Generated by Django 4.2.13 on 2026-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_scuola_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scuola',
            name='tipologia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipologia'),
        ),
    ]
